/**
 * IP2Region 中文国家名 → ECharts 世界地图英文国家名 映射
 * ECharts 内置世界地图使用 Natural Earth 英文国家名
 */
export const countryNameMap: Record<string, string> = {
  '中国': 'China',
  '美国': 'United States of America',
  '日本': 'Japan',
  '韩国': 'South Korea',
  '英国': 'United Kingdom',
  '德国': 'Germany',
  '法国': 'France',
  '俄罗斯': 'Russia',
  '加拿大': 'Canada',
  '澳大利亚': 'Australia',
  '印度': 'India',
  '巴西': 'Brazil',
  '意大利': 'Italy',
  '西班牙': 'Spain',
  '墨西哥': 'Mexico',
  '印度尼西亚': 'Indonesia',
  '土耳其': 'Turkey',
  '荷兰': 'Netherlands',
  '瑞士': 'Switzerland',
  '沙特阿拉伯': 'Saudi Arabia',
  '阿根廷': 'Argentina',
  '瑞典': 'Sweden',
  '波兰': 'Poland',
  '比利时': 'Belgium',
  '泰国': 'Thailand',
  '奥地利': 'Austria',
  '挪威': 'Norway',
  '以色列': 'Israel',
  '爱尔兰': 'Ireland',
  '新加坡': 'Singapore',
  '马来西亚': 'Malaysia',
  '菲律宾': 'Philippines',
  '丹麦': 'Denmark',
  '哥伦比亚': 'Colombia',
  '南非': 'South Africa',
  '芬兰': 'Finland',
  '智利': 'Chile',
  '罗马尼亚': 'Romania',
  '捷克': 'Czech Rep.',
  '葡萄牙': 'Portugal',
  '新西兰': 'New Zealand',
  '希腊': 'Greece',
  '匈牙利': 'Hungary',
  '越南': 'Vietnam',
  '孟加拉': 'Bangladesh',
  '巴基斯坦': 'Pakistan',
  '埃及': 'Egypt',
  '尼日利亚': 'Nigeria',
  '乌克兰': 'Ukraine',
  '秘鲁': 'Peru',
  '哈萨克斯坦': 'Kazakhstan',
  '伊朗': 'Iran',
  '伊拉克': 'Iraq',
  '阿联酋': 'United Arab Emirates',
  '委内瑞拉': 'Venezuela',
  '缅甸': 'Myanmar',
  '柬埔寨': 'Cambodia',
  '老挝': 'Lao PDR',
  '蒙古': 'Mongolia',
  '朝鲜': 'Dem. Rep. Korea',
  '尼泊尔': 'Nepal',
  '斯里兰卡': 'Sri Lanka',
  '肯尼亚': 'Kenya',
  '坦桑尼亚': 'Tanzania',
  '乌干达': 'Uganda',
  '摩洛哥': 'Morocco',
  '阿尔及利亚': 'Algeria',
  '突尼斯': 'Tunisia',
  '利比亚': 'Libya',
  '加纳': 'Ghana',
  '塞内加尔': 'Senegal',
  '喀麦隆': 'Cameroon',
  '厄瓜多尔': 'Ecuador',
  '玻利维亚': 'Bolivia',
  '巴拉圭': 'Paraguay',
  '乌拉圭': 'Uruguay',
  '古巴': 'Cuba',
  '多米尼加': 'Dominican Rep.',
  '危地马拉': 'Guatemala',
  '洪都拉斯': 'Honduras',
  '萨尔瓦多': 'El Salvador',
  '尼加拉瓜': 'Nicaragua',
  '哥斯达黎加': 'Costa Rica',
  '巴拿马': 'Panama',
  '牙买加': 'Jamaica',
  '冰岛': 'Iceland',
  '卢森堡': 'Luxembourg',
  '塞尔维亚': 'Serbia',
  '克罗地亚': 'Croatia',
  '斯洛文尼亚': 'Slovenia',
  '斯洛伐克': 'Slovakia',
  '保加利亚': 'Bulgaria',
  '白俄罗斯': 'Belarus',
  '立陶宛': 'Lithuania',
  '拉脱维亚': 'Latvia',
  '爱沙尼亚': 'Estonia',
  '格鲁吉亚': 'Georgia',
  '亚美尼亚': 'Armenia',
  '阿塞拜疆': 'Azerbaijan',
  '乌兹别克斯坦': 'Uzbekistan',
  '土库曼斯坦': 'Turkmenistan',
  '吉尔吉斯坦': 'Kyrgyzstan',
  '塔吉克斯坦': 'Tajikistan',
  '阿富汗': 'Afghanistan',
  '约旦': 'Jordan',
  '黎巴嫩': 'Lebanon',
  '叙利亚': 'Syria',
  '也门': 'Yemen',
  '阿曼': 'Oman',
  '卡塔尔': 'Qatar',
  '巴林': 'Bahrain',
  '科威特': 'Kuwait',
  '苏丹': 'Sudan',
  '埃塞俄比亚': 'Ethiopia',
  '索马里': 'Somalia',
  '刚果': 'Dem. Rep. Congo',
  '安哥拉': 'Angola',
  '莫桑比克': 'Mozambique',
  '赞比亚': 'Zambia',
  '津巴布韦': 'Zimbabwe',
  '博茨瓦纳': 'Botswana',
  '纳米比亚': 'Namibia',
  '马达加斯加': 'Madagascar',
  '马里': 'Mali',
  '尼日尔': 'Niger',
  '乍得': 'Chad',
  '布基纳法索': 'Burkina Faso',
  '几内亚': 'Guinea',
  '塞拉利昂': 'Sierra Leone',
  '利比里亚': 'Liberia',
  '马拉维': 'Malawi',
  '卢旺达': 'Rwanda',
  '中非': 'Central African Rep.',
  '巴布亚新几内亚': 'Papua New Guinea',
  '斐济': 'Fiji',
  // 台湾地区
  '台湾': 'Taiwan',
  '中国台湾': 'Taiwan',
  // 港澳
  '中国香港': 'China',
  '中国澳门': 'China',
  '香港': 'China',
  '澳门': 'China',
}

/**
 * IP2Region 省份名 → DataV GeoJSON 省份全名 映射
 * IP2Region 返回简短名（如"广东"），GeoJSON 使用全名（如"广东省"）
 */
export const provinceNameMap: Record<string, string> = {
  '北京': '北京市',
  '天津': '天津市',
  '上海': '上海市',
  '重庆': '重庆市',
  '河北': '河北省',
  '山西': '山西省',
  '辽宁': '辽宁省',
  '吉林': '吉林省',
  '黑龙江': '黑龙江省',
  '江苏': '江苏省',
  '浙江': '浙江省',
  '安徽': '安徽省',
  '福建': '福建省',
  '江西': '江西省',
  '山东': '山东省',
  '河南': '河南省',
  '湖北': '湖北省',
  '湖南': '湖南省',
  '广东': '广东省',
  '海南': '海南省',
  '四川': '四川省',
  '贵州': '贵州省',
  '云南': '云南省',
  '陕西': '陕西省',
  '甘肃': '甘肃省',
  '青海': '青海省',
  '台湾': '台湾省',
  '内蒙古': '内蒙古自治区',
  '广西': '广西壮族自治区',
  '西藏': '西藏自治区',
  '宁夏': '宁夏回族自治区',
  '新疆': '新疆维吾尔自治区',
  '香港': '香港特别行政区',
  '澳门': '澳门特别行政区',
}
